### PR TITLE
Added 2 missing permissions

### PR DESCRIPTION
**Pull request by Hype3808**
https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags

## Summary

Add `START_EMBEDDED_ACTIVITIES` and `MODERATE_MEMBERS` permissions.

Can be found on *https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags*

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

## Confirmations

- [x] I have checked the open PRs and no PR exists like this one.
- [x] My PR focuses on only one issue/change.

### CODE REVIEW

**Comment by nerdguyahmad** [comment]
Please update the factory class methods too. (`Permissions.all`, `Permissions.all_channels` and other **relevant** methods) with new permissions value.

**Comment by nerdguyahmad** [comment]
`all_channel` & `general` too.

**Comment by Hype3808** [comment]
They are not needed to be changed *https://discord.com/developers/docs/topics/permissions#permissions*

image

**Comment by Hype3808** [comment]
@nerdguyahmad `all_channel` and `general` are not needed to be changed isn't it?

**Pull request merged**
