### PR TITLE
Add Member.timeout

### PR DESCRIPTION
**Pull request by MarzaElise**
## Summary
Added `Member.timeout` for ease of use

## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

## Confirmations

- [x] I have checked the open PRs and no PR exists like this one.
- [x] My PR focuses on only one issue/change.

### CODE REVIEW

**Comment by MarzaElise** [comment]
how tf do i request review- did github change UI?

**Review by VincentRPS — APPROVED** [review]

**Review by Hype3808 — APPROVED** [review]
lgtm needa wait for @nerdguyahmad 's opinion tho...

**Comment by Hype3808** [comment]
needa wait for #33 to be merged

**Comment by nerdguyahmad** [comment]
I'm not fan of this, It has many inconsistencies.

**Pull request closed without merging**
