### PR TITLE
Bump aiohttp to a later version

### PR DESCRIPTION
**Pull request by Hype3808**
## Summary
Bump aiohttp to a later version

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

## Confirmations

- [x] I have checked the open PRs and no PR exists like this one.
- [x] My PR focuses on only one issue/change.

### CODE REVIEW

**Comment by nerdguyahmad** [comment]
We'll have to make sure first that there aren't any breaking changes that potentially break something.

**Comment by Hype3808** [comment]
yes, i haven't tested it.

**Comment by Hype3808** [comment]
But we kinda only needa worried about application commands

**Comment by Hype3808** [comment]
Tested on slash commands (everything in the `application_commands` directory). Works fine for me

**Comment by nerdguyahmad** [comment]
There are many other much important things then application commands. FYI, This library uses aiohttp websockets too.

**Comment by Hype3808** [comment]
Oh i see. But for now i have only tested on application commands. Which uses aiohttp websockets? Webhook or wut?

**Comment by Hype3808** [comment]
eh shit... i deleted the branch... i ma open another one later

**Pull request closed without merging**
